name: Run unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: moneystack
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U root"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
      id: go

    - name: Install Go Lang Migration
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-386.tar.gz | tar xvz
        sudo mv migrate /usr/bin/
        which migrate

    - name: Wait for Postgres
      run: |
        until pg_isready -h localhost -p 5432 -U root; do
          echo "Waiting for postgres service to be ready..."
          sleep 5
        done
        echo "Postgres is ready!"

    - name: Run Migrations
      run: make migrateup
      env:
        DB_SOURCE: postgresql://root:root@localhost:5432/moneystack?sslmode=disable

    - name: Run Tests
      run: make test
      env:
        DB_SOURCE: postgresql://root:root@localhost:5432/moneystack?sslmode=disable